# Generated by Django 5.1.3 on 2024-11-20 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goapp', '0003_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='datetime',
            field=models.DateTimeField(default='2024-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
